---
roles:
  - src: https://github.com/36node-roles/alidns
    name: 36node.alidns
    version: main

  - src: https://github.com/36node-roles/mongodb
    name: 36node.mongodb
    version: main

collections:
  - name: community.kubernetes
    version: 1.2.1
  - community.general
  - ansible.posix
  - community.crypto
