# This workflow will run tests using node and then publish a package to NPM Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: k8s apply pod&ingress

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
      - uses: actions/checkout@v2
      - name: Apply pod
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.ALI_K8S_CONFIG }}
          args: apply -f k8s/pod.yaml
      - name: Apply ingress
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.ALI_K8S_CONFIG }}
          args: apply -f k8s/pod.yaml
