# This workflow will run tests using node and then publish a package to NPM Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Pr Dispatch

on:
  repository_dispatch:
    types: [pr-deploy]

jobs:
  build-test:
    runs-on: ubuntu-18.04
    env:
      DEVOPS_PATH: cc-devops-test
      DOMAIN_BASE: 36node.com
      SSH_SERVER: 218.78.25.41
      SSH_PORT: 8022
      SSH_USER: root
    steps:
      - uses: actions/checkout@v2
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: "YYYYMMDDHHmmss"
      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-text: "${{ github.event.client_payload.repo }}"
          "-": _
      - name: Execute SSH commmands on remote server
        uses: tarunjangra/ssh-remote-cmd@v1
        with:
          command: |
            cd ${{ env.DEVOPS_PATH }}
            yarn site:${{ github.event.client_payload.org }} -e namespace=${{ github.event.client_payload.namespace }} -e ${{ github.event.client_payload.repo }}_version=${{ github.event.client_payload.tag }} -e ${{ steps.sub.outputs.result }}_time=${{ steps.time.outputs.time }}
          host: ${{ env.SSH_SERVER }}
          port: ${{ env.SSH_PORT }}
          user: ${{ env.SSH_USER }}
          key: ${{ secrets.CTYUN_PRIVATE_KEY}}
      - name: Show env
        run: echo "${{ github.event.client_payload.open }}"
      - name: Create pr comment
        if: ${{ github.event.client_payload.open }}
        env:
          URL: https://api.github.com/repos/${{ github.event.client_payload.org }}/${{ github.event.client_payload.repo }}/issues/${{ github.event.client_payload.number }}/comments
          DEPLOY_DOMAIN: ${{ github.event.client_payload.namespace }}.${{ env.DOMAIN_BASE }}
          DEPLOY_URL: ${{ github.event.client_payload.deploy_url_prefix }}.${{ env.DEPLOY_DOMAIN }}${{ github.event.client_payload.deploy_url_suffix }}
        uses: fjogeleit/http-request-action@master
        with:
          url: ${{ env.URL }}
          method: "POST"
          customHeaders: '{"Accept":"application/vnd.github.v3+json","Authorization":"token ${{ secrets.PR_TOKEN }}"}'
          data: '{"body":"该pr部署在${{ github.event.client_payload.namespace }}命名空间上，domain为，url链接为${{ env.DEPLOY_URL }}\n工程内的其他项目domain与该pr的domain相同"}'
