# This workflow will run tests using node and then publish a package to NPM Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Dispatch deploy

on:
  repository_dispatch:
    types: [pr-deploy]

jobs:
  build-test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: show
        run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      # - name: Execute SSH commmands on remote server
      #   uses: tarunjangra/ssh-remote-cmd@v1
      #   env:
      #     SERVER: 218.78.25.41
      #     PORT: 8022
      #     DEVOPS_PATH: z-ctyun-devops
      #     NAMESPACE: "${{ github.event.client_payload.owner }}-${{ github.event.client_payload.repo }}-${{ github.event.client_payload.tag }}"
      #   with:
      #     command: |
      #       cd ${{ env.DEVOPS_PATH }}
      #       yarn site:${{ github.event.client_payload.owner }} -e namespace=${{ env.NAMESPACE }} -e ${{ github.event.client_payload.repo }}=${{ github.event.client_payload.tag }}
      #     host: ${{ env.SERVER }}
      #     port: ${{ env.PORT }}
      #     user: root
      #     key: ${{ secrets.CTYUN_PRIVATE_KEY}}
