---
- name: Namespace for devops-test
  community.kubernetes.k8s:
    state: "{{ state }}"
    name: "{{ namespace }}"
    api_version: v1
    kind: Namespace

- name: Webhook service
  community.kubernetes.k8s:
    state: "{{ state }}"
    namespace: "{{ namespace }}"
    template: "{{ item }}"
  with_items:
    - devops-test.yml.j2
    - ingress.yml.j2
  tags:
    - devops-test
